start:
	g++ *.cpp -lmysqlclient -Wno-write-strings -fPIC -shared -o ../openspy/modules/playersearch.so -I.. ../common/*.cpp ../common/*.c
debug:
	g++ *.cpp -lmysqlclient -Wno-write-strings -ggdb -fPIC -shared -o ../openspy/modules/playersearch.so -I.. ../common/*.cpp ../common/*.c
