start:
	g++ *.cpp -lmysqlclient -Wno-write-strings -shared -o ../openspy/modules/playersearch.so -I.. ../common/*.cpp ../common/*.c
debug:
	g++ *.cpp -lmysqlclient -Wno-write-strings -ggdb -shared -o ../openspy/modules/playersearch.so -I.. ../common/*.cpp ../common/*.c
