start:
	g++ *.cpp -lmysqlclient -lGeoIP -Wno-write-strings -shared -o ../openspy/modules/qr.so -I.. ../common/*.cpp ../common/*.c
debug:
	g++ *.cpp -lmysqlclient -lGeoIP -Wno-write-strings -ggdb -shared -o ../openspy/modules/qr.so -I.. ../common/*.cpp ../common/*.c
